# ⚠️ Only non-root builds (Can be used on rooted device).

[YT] # Default patchs are applied, Exception for lines 4 & 5:
included-patches = "'Custom branding' 'Change header'"
excluded-patches = "'Hide cast button' 'Swipe controls'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music] # Default patches are applied:
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Spotify-XManager] # Exclusive patches are applied, line 13:
exclusive-patches = true
included-patches = "'Spoof signature'"
fileport-dlurl = "https://fileport.io/KqaSfLUgBeqG"
